import Head from 'next/head'
import Image from 'next/image'
import Avatar from '../components/avatar'

export default function Home() {
    return (
        <div>
            <Head>
                <title>Google Clone</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* Header */}
            <header className="flex w-full p-5 justify-between text-sm text-gray-700">
                {/* Left Div */}
                <div className="flex space-x-4 items-center">
                    <p className="link">About</p>
                    <p className="link">Store</p>
                </div>

                {/* Right Div */}
                <div className="flex space-x-4 items-center">
                    <p className="link">Gmail</p>
                    <p className="link">Images</p>
                </div>

                {/* Icon */}

                {/* Avatar */}
                <Avatar url="https://coaching.papareact.com/ai9" />
            </header>

            <h1 className="p-48">Let's build Google clone with NEXT.js and Tailwind CSS</h1>
        </div>
    )
}
