import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
    return (
        <div>
            <Head>
                <title>Google Clone</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* Header */}
            <header>
                {/* Left Div */}
                <p>About</p>
                <p>Store</p>

                {/* Right Div */}
                <p>Gmail</p>
                <p>Images</p>
            </header>

            <h1 className="p-48">Let's build Google clone with NEXT.js and Tailwind CSS</h1>
        </div>
    )
}
